In [26]:
%config IPCompleter.greedy = True

In [27]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

In [104]:
import chardet
import pandas as pd

def find_encoding(fname):
    r_file = open(fname, 'rb').read()
    result = chardet.detect(r_file)
    charenc = result['encoding']
    return charenc

In [105]:
my_encoding = find_encoding('companies.txt')

print(my_encoding)

Windows-1254

In [106]:
my_encoding = find_encoding('rounds2.csv')
print(my_encoding)

Windows-1254

In [75]:
companies = pd.read_csv('companies.txt', encoding = 'ISO-8859-1', sep='\t')

In [96]:
companies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66368 entries, 0 to 66367
Data columns (total 10 columns):
permalink        66368 non-null object
name             66367 non-null object
homepage_url     61310 non-null object
category_list    63220 non-null object
status           66368 non-null object
country_code     59410 non-null object
state_code       57821 non-null object
region           58338 non-null object
city             58340 non-null object
founded_at       51147 non-null object
dtypes: object(10)
memory usage: 5.1+ MB

In [91]:
companies.shape

(66368, 10)

In [92]:
companies.columns

Index(['permalink', 'name', 'homepage_url', 'category_list', 'status',
       'country_code', 'state_code', 'region', 'city', 'founded_at'],
      dtype='object')

Notes


permalink - Index

In [93]:
companies.head()

,permalink,name,homepage_url,category_list,status,country_code,state_code,region,city,founded_at
0,/Organization/-Fame,#fame,http://livfame.com,Media,operating,IND,16,Mumbai,Mumbai,NaN
1,/Organization/-Qounter,:Qounter,http://www.qounter.com,Application Platforms|Real Time|Social Network...,operating,USA,DE,DE - Other,Delaware City,04-09-2014
2,/Organization/-The-One-Of-Them-Inc-,"(THE) ONE of THEM,Inc.",http://oneofthem.jp,Apps|Games|Mobile,operating,NaN,NaN,NaN,NaN,NaN
3,/Organization/0-6-Com,0-6.com,http://www.0-6.com,Curated Web,operating,CHN,22,Beijing,Beijing,01-01-2007
4,/Organization/004-Technologies,004 Technologies,http://004gmbh.de/en/004-interact,Software,operating,USA,IL,"Springfield, Illinois",Champaign,01-01-2010

In [94]:
len(companies.permalink.str.lower())

66368

In [95]:
companies['permalink'] = companies['permalink'].str.lower()

In [108]:
companies.head(10)

,permalink,name,homepage_url,category_list,status,country_code,state_code,region,city,founded_at
0,/organization/-fame,#fame,http://livfame.com,Media,operating,IND,16,Mumbai,Mumbai,NaN
1,/organization/-qounter,:Qounter,http://www.qounter.com,Application Platforms|Real Time|Social Network...,operating,USA,DE,DE - Other,Delaware City,04-09-2014
2,/organization/-the-one-of-them-inc-,"(THE) ONE of THEM,Inc.",http://oneofthem.jp,Apps|Games|Mobile,operating,NaN,NaN,NaN,NaN,NaN
3,/organization/0-6-com,0-6.com,http://www.0-6.com,Curated Web,operating,CHN,22,Beijing,Beijing,01-01-2007
4,/organization/004-technologies,004 Technologies,http://004gmbh.de/en/004-interact,Software,operating,USA,IL,"Springfield, Illinois",Champaign,01-01-2010
5,/organization/01games-technology,01Games Technology,http://www.01games.hk/,Games,operating,HKG,NaN,Hong Kong,Hong Kong,NaN
6,/organization/0ndine-biomedical-inc,Ondine Biomedical Inc.,http://ondinebio.com,Biotechnology,operating,CAN,BC,Vancouver,Vancouver,01-01-1997
7,/organization/0xdata,H2O.ai,http://h2o.ai/,Analytics,operating,USA,CA,SF Bay Area,Mountain View,01-01-2011
8,/organization/1,One Inc.,http://whatis1.com,Mobile,operating,USA,CA,SF Bay Area,San Francisco,01-08-2011
9,/organization/1-2-3-listo,"1,2,3 Listo",http://www.123listo.com,E-Commerce,operating,CHL,12,Santiago,Las Condes,01-01-2012

Q. How many unique companies are present in companies?
Answer = 66103

In [107]:
len(companies.permalink.unique())

66368

In [109]:
len(companies.name.unique())

66103

In [113]:
companies[companies['name'].duplicated()]

,permalink,name,homepage_url,category_list,status,country_code,state_code,region,city,founded_at
282,/organization/3divaz-3,3DIVAZ,http://www.3divaz.ch/Home,NaN,operating,CHE,1,CHE - Other,Wildegg,01-07-2014
1527,/organization/adtena-2,Adtena,http://adtena.com,NaN,closed,NaN,NaN,NaN,NaN,15-11-2014
1996,/organization/agora-6,Agora,https://www.agora.co,Android|Apps|Internet|Mobile,operating,USA,NY,New York City,New York,01-07-2013
3006,/organization/amicus-co,Amicus,http://www.amicus.co,Apps|Mobile|Mobile Commerce,operating,IND,7,New Delhi,New Delhi,01-01-2015
3091,/organization/amplitude-2,Amplitude,http://amplitude-technologies.com/,Electronics,operating,FRA,A8,Ãâ°vry,Ãvry,01-01-2001
3257,/organization/anews-inc,"Anews, Inc.",http://www.anews.com,Blogging Platforms|News|Social Media|Social Ne...,operating,USA,CA,SF Bay Area,Palo Alto,01-07-2013
3943,/organization/aps-llc,APS,NaN,Real Estate,operating,USA,GA,Macon,Griffin,31-03-2011
3966,/organization/aptible-2,Aptible,NaN,NaN,closed,NaN,NaN,NaN,NaN,NaN
3983,/organization/apx-2,APX,http://www.apx.com/,Energy Management|Environmental Innovation,operating,USA,CA,SF Bay Area,San Jose,NaN
4121,/organization/archive-2,Archive,http://www.archive.com,Apps|B2B|Service Providers,closed,USA,CA,Los Angeles,Culver City,NaN
4169,/organization/ardian-inc,Ardian,http://www.ardian.com,Health Care,acquired,USA,CA,SF Bay Area,Mountain View,01-01-2003
4482,/organization/arvegenix-2,Arvegenix,http://www.arvegenix.com/,Industrial|Oil|Renewable Energies,operating,USA,MO,St. Louis,St Louis,NaN
4992,/organization/augur-2,Augur,http://www.augur.net,Bitcoin|Business Services|Internet|Market Rese...,operating,USA,CA,SF Bay Area,San Francisco,01-01-2015
4996,/organization/august-2,August,http://www.agst.co,Digital Media|Social Media,operating,USA,CA,Anaheim,Newport Beach,26-08-2014
5147,/organization/autopilot-2,Autopilot,http://www.autopilothq.com,Lead Management|SaaS|Sales and Marketing|Small...,operating,USA,CA,SF Bay Area,San Francisco,13-02-2013
5674,/organization/bactest-2,Bactest,NaN,NaN,closed,NaN,NaN,NaN,NaN,NaN
5876,/organization/bark-co,Bark & Co,http://bark.co,Pets,operating,USA,NY,New York City,New York,NaN
5958,/organization/baton-handoff,Baton,http://www.batonmed.com,Hospitals,operating,USA,MD,Baltimore,Baltimore,01-01-2014
6423,/organization/bentonow,Bento,https://bentonow.com/,Apps,operating,USA,CA,SF Bay Area,San Francisco,09-03-2015
7450,/organization/blink-4,Blink,http://www.blinnnk.com/,Software,operating,JPN,18,JPN - Other,China,01-01-2014
7451,/organization/blink-7,Blink,http://blinkforhome.com,Electronics,operating,USA,MA,Boston,Boston,NaN
7452,/organization/blink-9,Blink,http://www.flyblink.com/,Location Based Services|Service Providers,operating,GBR,N7,Camberley,Camberley,NaN
7483,/organization/bliss-4,Bliss,http://blissmobilemassage.com/,Consulting,operating,USA,CA,Los Angeles,Los Angeles,12-03-2015
7538,/organization/bloodhound-2,Bloodhound,http://www.bloodhoundinc.com/,Application Platforms|Medical|Services,closed,USA,NC,Raleigh,Durham,NaN
7921,/organization/bolt-io,Bolt,http://bolt.io,Venture Capital,operating,USA,MA,Boston,Boston,01-02-2013
8055,/organization/boomerang,Boomerang,http://rang.com,Advertising|Gift Card|Incentives|Mobile,closed,USA,IL,Chicago,Chicago,NaN
8092,/organization/booster-3,Booster,http://www.boosteragtech.com,Agriculture,operating,USA,NY,New York City,New York,14-09-2014
8409,/organization/bread-labs,Bread,http://www.bre.ad,Advertising,acquired,USA,CA,SF Bay Area,San Francisco,01-01-2011
8437,/organization/breeze-4,Breeze,http://www.joinbreeze.com,Cars|Services|Startups,operating,USA,CA,SF Bay Area,San Francisco,01-01-2014
8484,/organization/bridg-2,Bridg,http://www.bridgtheapp.com,Apps|FinTech|Payments,operating,ARE,3,Dubai,Dubai,01-01-2013
...,...,...,...,...,...,...,...,...,...,...
59543,/organization/trove-3,Trove,http://trove.com,Internet|News,operating,USA,DC,"Washington, D.C.",Washington,01-01-2009
59544,/organization/trove-4,Trove,http://www.troveup.com,3D Printing|Consumer Internet|E-Commerce,operating,USA,NY,New York City,New York,01-11-2014
59924,/organization/tvibes,TVibes,http://www.tvibes.com,NaN,closed,NaN,NaN,NaN,NaN,01-01-2015
60012,/organization/twistlock-2,Twistlock,https://www.twistlock.io/,Security,operating,USA,CA,SF Bay Area,San Francisco,NaN
60187,/organization/ubiq-toolbox,Ubiq,https://www.getubiq.com/en/,Facebook Applications|Local Advertising|Multi-...,operating,FRA,B8,Marseille,Marseille,17-03-2014
60489,/organization/united-capital-2,United Capital,http://uc.ge/,Financial Services,operating,GEO,19,Tbilisi,Tbilisi,15-01-2002
60584,/organization/university-of-pittsburgh-main,University of Pittsburgh,http://www.pitt.edu/,Education,operating,USA,PA,Pittsburgh,Pittsburgh,1787-01-01
60587,/organization/university-of-rochester-2,University of Rochester,http://www.rochester.edu,NaN,operating,USA,NY,"Rochester, New York",Rochester,1850-01-01
60727,/organization/upstream-technologies-2,Upstream Technologies,http://www.upstream.net,Technology,operating,USA,MA,Boston,Boston,NaN
60729,/organization/uptake-3,Uptake,http://www.uptake.com,Analytics|Big Data|Internet of Things,operating,USA,IL,Chicago,Chicago,01-01-2014
61104,/organization/vanford-inc,Sesh,http://www.seshtutoring.com,Education|Peer-to-Peer,operating,USA,CA,SF Bay Area,Palo Alto,31-07-2014
61426,/organization/ventrix-2,Ventrix,http://www.ventrix.com.br,Biotechnology|Health Care|Medical,closed,NaN,NaN,NaN,NaN,01-01-2005
61603,/organization/versus-llc,Versus,http://versusgamingnetwork.com,Apps|Games|Mobile Games,operating,NaN,NaN,NaN,NaN,21-08-2013
61656,/organization/vessel-2,Vessel,http://www.vessel.com/,Content|Content Creators|Internet|Video,operating,USA,CA,SF Bay Area,San Francisco,01-01-2013
61726,/organization/via-transportation,Via,http://www.ridewithvia.com,Apps|Real Time|Software|Technology|Transportation,operating,USA,NY,New York City,New York,01-01-2012
61736,/organization/viacord-2,ViaCell,http://www.viacord.com/,Biotechnology,operating,USA,MA,Boston,Boston,NaN
62919,/organization/waicai,Wacai,http://www.wacai.com,Finance|FinTech,operating,CHN,2,Hangzhou,Hangzhou,NaN
63239,/organization/we-tribute,Tribute,http://www.tribute.co,Software,operating,USA,NY,New York City,Brooklyn,01-06-2014
63285,/organization/weave-2,Weave,http://weave.in,Location Based Services|Mobile|Professional Ne...,operating,USA,CA,SF Bay Area,San Francisco,01-01-2013
63551,/organization/wello-2,Wello,NaN,NaN,operating,NaN,NaN,NaN,NaN,NaN
64150,/organization/wisenetworks,Wise Connect,http://www.wiseconnect.pt,Agriculture|Mobile,operating,PRT,14,Porto,Porto,01-05-2012
64276,/organization/wonder-3,Wonder,NaN,NaN,closed,NaN,NaN,NaN,NaN,NaN
64341,/organization/worcester-polytechnic-institute-3,Worcester Polytechnic Institute,http://www.wpi.edu/,NaN,operating,USA,MA,Worcester,Worcester,01-01-2014
64375,/organization/workface,Workface,http://www.workface.com,Chat|Enterprises|Identity|Software|Video,operating,USA,MN,Minneapolis,Minneapolis,01-10-2007
64482,/organization/wormhole-it,Wormhole,http://www.wormholeit.com,College Campuses|Corporate Training|EdTech|Edu...,operating,ARG,7,Buenos Aires,Buenos Aires,28-11-2007
64571,/organization/wunder-3,Wunder,NaN,Alumni,operating,NaN,NaN,NaN,NaN,NaN
64572,/organization/wundercar,Wunder,http://www.wunder.org,Apps|Emerging Markets|Marketplaces|Mobile Comm...,operating,DEU,4,Hamburg,Hamburg,01-11-2013
65799,/organization/zenpayroll,Gusto,https://gusto.com/,Financial Services|Personal Finance|Software,operating,USA,CA,SF Bay Area,San Francisco,01-01-2011
65899,/organization/zestyapp,Zesty,http://www.zesty.com/,Health and Wellness|Logistics|Organic Food|Spe...,operating,USA,CA,SF Bay Area,San Francisco,04-11-2013
66029,/organization/zingbox-2,ZingBox,NaN,Services|Solar,operating,NaN,NaN,NaN,NaN,NaN

In [114]:
rounds2 = pd.read_csv('rounds2.csv', encoding = 'ISO-8859-1')

In [115]:
rounds2.head()

,company_permalink,funding_round_permalink,funding_round_type,funding_round_code,funded_at,raised_amount_usd
0,/organization/-fame,/funding-round/9a01d05418af9f794eebff7ace91f638,venture,B,05-01-2015,10000000.0
1,/ORGANIZATION/-QOUNTER,/funding-round/22dacff496eb7acb2b901dec1dfe5633,venture,A,14-10-2014,NaN
2,/organization/-qounter,/funding-round/b44fbb94153f6cdef13083530bb48030,seed,NaN,01-03-2014,700000.0
3,/ORGANIZATION/-THE-ONE-OF-THEM-INC-,/funding-round/650b8f704416801069bb178a1418776b,venture,B,30-01-2014,3406878.0
4,/organization/0-6-com,/funding-round/5727accaeaa57461bd22a9bdd945382d,venture,A,19-03-2008,2000000.0

In [116]:
rounds2.columns

Index(['company_permalink', 'funding_round_permalink', 'funding_round_type',
       'funding_round_code', 'funded_at', 'raised_amount_usd'],
      dtype='object')

In [117]:
rounds2.shape

(114949, 6)

In [118]:
rounds2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114949 entries, 0 to 114948
Data columns (total 6 columns):
company_permalink          114949 non-null object
funding_round_permalink    114949 non-null object
funding_round_type         114949 non-null object
funding_round_code         31140 non-null object
funded_at                  114949 non-null object
raised_amount_usd          94959 non-null float64
dtypes: float64(1), object(5)
memory usage: 5.3+ MB

In [119]:
rounds2['company_permalink'] = rounds2['company_permalink'].str.lower()

In [120]:
rounds2.head(10)

,company_permalink,funding_round_permalink,funding_round_type,funding_round_code,funded_at,raised_amount_usd
0,/organization/-fame,/funding-round/9a01d05418af9f794eebff7ace91f638,venture,B,05-01-2015,10000000.0
1,/organization/-qounter,/funding-round/22dacff496eb7acb2b901dec1dfe5633,venture,A,14-10-2014,NaN
2,/organization/-qounter,/funding-round/b44fbb94153f6cdef13083530bb48030,seed,NaN,01-03-2014,700000.0
3,/organization/-the-one-of-them-inc-,/funding-round/650b8f704416801069bb178a1418776b,venture,B,30-01-2014,3406878.0
4,/organization/0-6-com,/funding-round/5727accaeaa57461bd22a9bdd945382d,venture,A,19-03-2008,2000000.0
5,/organization/004-technologies,/funding-round/1278dd4e6a37fa4b7d7e06c21b3c1830,venture,NaN,24-07-2014,NaN
6,/organization/01games-technology,/funding-round/7d53696f2b4f607a2f2a8cbb83d01839,undisclosed,NaN,01-07-2014,41250.0
7,/organization/0ndine-biomedical-inc,/funding-round/2b9d3ac293d5cdccbecff5c8cb0f327d,seed,NaN,11-09-2009,43360.0
8,/organization/0ndine-biomedical-inc,/funding-round/954b9499724b946ad8c396a57a5f3b72,venture,NaN,21-12-2009,719491.0
9,/organization/0xdata,/funding-round/383a9bd2c04f7038bb543ccef5ba3eae,seed,NaN,22-05-2013,3000000.0

In [121]:
len((rounds2.company_permalink).unique())

66370

In [122]:
len((rounds2.funding_round_permalink).unique())

114949

How many unique companies are present in companies?

In [123]:
len(companies.name.unique())

66103

In the companies data frame, which column can be used as the unique key for each company? Write the name of the column.

In [43]:
len(companies.permalink.unique())

66368